### ISSUE TITLE
Android: Can't connect to private server with private certificate

### ISSUE THREAD

**Issue by IeP4nieF** [casimir/frigoligo#201] opened 2024-05-26 18:12 UTC
Hi,

I'm hosting a private wallabag instance in my lan with a private ip, private domain and a certificate from my private CA. I can connect and use this instance from any client (also Android) in my LAN with a browser.

But after installation of frigoligo (1.0.10) form f-droid on my Android I can't connect to the server.  After entering the server name in the first field ("Server address") nothing happens after tiping on "Check", but I get the message "Server unreachable".

In the logs of the wallabag-instance there are no connections attempts!

Please let me know if there is something I can do to debug this bug.

Best regards

**Comment by casimir** [comment] 2024-06-01 19:31
Would you mind sharing the server address you use?
You can reach me on matrix (@casimir:one.ems.host) or email (contact@casimir-lab.net) if you want to keep it private.

**Comment by SteveJos** [comment] 2024-07-03 20:29
I have the same issue connecting to self-hosted wallabag instance. Any updates regarding a solution? @casimir

**Comment by IeP4nieF** [comment] 2024-07-04 03:23
> Would you mind sharing the server address you use? You can reach me on matrix (@casimir:one.ems.host) or email ([contact@casimir-lab.net](mailto:contact@casimir-lab.net)) if you want to keep it private.

Sorry for my late answer.

The server address (either dns and ip) is private. The server is not reachable from the internet. The ip is 192.168.101.166. My private dns-server resolves the domain-name to this ip correctly. And again: With a web-browser I can reach and use my wallabag-server from any client in the LAN (the root-certificate was imported to the browser before).

**Comment by casimir** [comment] 2024-07-09 08:09
This issue will definitly be adressed but I will need some time to set up to reproduce correctly. Hopefully a `docker-compose` will do the trick.

In the meantime, isn't it possible to add the certificate to the OS too? IIRC you can add it to the Android Trust Store and it should apply globally.

**Comment by IeP4nieF** [comment] 2024-07-09 08:23
> This issue will definitly be adressed but I will need some time to set up to reproduce correctly. Hopefully a `docker-compose` will do the trick.

Thank you for addressing this!

> In the meantime, isn't it possible to add the certificate to the OS too? IIRC you can add it to the Android Trust Store and it should apply globally.

Sorry, I forgot to mention this. Of course the root-certificate of my CA is added as a trusted root-certificate to my Android. The described behaviour occurs with the root-certificate imported to my Android.

**Comment by casimir** [comment] 2024-08-08 15:24
The last available version (1.2.0) contains the fix for this issue. Can you make sure your app is updated and try again?

**Comment by casimir** [comment] 2024-08-10 13:05
Feel free to reopen if the problem still exists in the latest version.

**Comment by IeP4nieF** [comment] 2024-08-12 19:22
The issue is still the same. Also in Version 1.2.0.

First without checking "Accept self-signed certificates" (which must be the right option for me, because I imported the root-certificate of my CA in Android. In this sense my certificate of my wallabag-server is not self-singed from the view of the os.

In the logs of my webserver (nginx as a proxy to wallabag) there is still no entry in the `access.log.` Obviously frigoligo does still not try to contact my server.

After checking the "Accept self-signed certificates" there is one entry in `access.log` and also in the logs of wallabag:

    wallabag_1  | 172.18.0.1 - - [12/Aug/2024:19:09:42 +0000] "GET /api/info HTTP/1.0" 200 82 "-" "frigoligo/1.2.0+35"

But frigoligo still "says" "Server unreachable" and nothing happens.

How can I reopen this issue? There is only a button "Comment".

**Comment by casimir** [comment] 2024-08-13 12:28
I have a feeling that the issue isn't with the certificate. The "Server unreachable" error is actually a handshake exception internally, it can be another issue.

I can't think of why the app would show an error but still performs the info request. 

Some troubleshooting ideas:
1. Does it work if first check is done with "Accept self-signed certificates" checked? After you killed the app.
2. What does `curl -k https://YOUR_DOMAIN/api/info` say?
3. Is something in your setup using the `User-Agent` header?

**Comment by casimir** [comment] 2024-11-08 12:36
This issue seems stale. Feel free to reopen if this is still occurring and you have more information to provide.

**Comment by Aditya137x** [comment] 2024-12-16 00:18
Hi, I have self-hosted wallabag using docker and run it just locally. Usually I use http://(ip addr):(port)/login to access wallabag inside a browser. But it doesn't work in frigoligo.

**Comment by casimir** [comment] 2024-12-16 18:17
Hey, do you authorized all certificate (checkbox under the server address in the login form)? And if so how does it "not work"? What error do you get?

**Comment by Aditya137x** [comment] 2024-12-16 19:44
Yes I have checked the box "Accept self-signed certificates".  It gives error Server unreachable.

**Comment by casimir** [comment] 2024-12-16 21:19
Can you try to run `curl -k http://(ip addr):(port)/api/info` to see how it goes?

**Comment by Aditya137x** [comment] 2024-12-16 23:51
This is what I got.

`{"appname":"wallabag","version":"2.6.10","allowed_registration":false}`

**Comment by casimir** [comment] 2024-12-20 12:52
After some investigation I found out that the app will mostly not work in `http` (in opposition to `https`). So I reopen this issue as a bug,

**Closed** 2024-12-20 13:00 UTC
Labels: missing feature

**Comment by casimir** [comment] 2025-01-12 15:32
Released with v2.2.0.
